language : node_js
sudo: false
services: 
  - mongodb 

# before_script:
#   - echo "replSet = myReplSetName" | sudo tee -a /etc/mongodb.conf
#   - sudo service mongodb restart
#   - sleep 20
#   - mongo --eval 'rs.initiate()'
#   - sleep 15

  
#   - docker
# before_script:
#   - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10
#   - echo 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' | sudo tee /etc/apt/sources.list.d/mongodb.list
#   - sudo apt-get update
#   - sudo apt-get install -y mongodb-org=2.6.6 mongodb-org-server=2.6.6 mongodb-org-shell=2.6.6 mongodb-org-mongos=2.6.6 mongodb-org-tools=2.6.6
#   - sleep 15 #mongo may not respond immediatly
#   - mongo --version

# env:
#   global:
#     - MONGODB_VERSION=2.6.10
# before_install:
#   - wget http://fastdl.mongodb.org/linux/mongodb-linux-x86_64-$MONGODB_VERSION.tgz
#   - tar xfz mongodb-linux-x86_64-$MONGODB_VERSION.tgz
#   - export PATH=`pwd`/mongodb-linux-x86_64-$MONGODB_VERSION/bin:$PATH
#   - mkdir -p data/db
#   - mongod --dbpath=data/db &
#   - sleep 3


# env:
#   global:
#     - MONGODB_VERSION=2.6.10
# install:
#   - wget http://fastdl.mongodb.org/linux/mongodb-linux-x86_64-$MONGODB_VERSION.tgz
#   - tar xfz mongodb-linux-x86_64-$MONGODB_VERSION.tgz
#   - export PATH=`pwd`/mongodb-linux-x86_64-$MONGODB_VERSION/bin:$PATH
#   - mkdir -p data/db
#   - mongod --dbpath=data/db &
#   - sleep 3
# script:
#   - mongo --eval 'db.hostInfo()'


# before_script:
#   - sleep 15
#   - mongo mydb_test --eval 'db.addUser("travis", "test");'